Repository marijadjurisic/airvironment-frontend-summer, pull requests merged in 2021-08, with the labels that each got.

#32 frontend/29 Display data on Averages page #29
  package-lock.json
  package.json
  src/assets/styles/components/MeasurementCard.scss
  src/assets/styles/pages/Averages.scss
  src/common/utils.js
  src/components/MeasurementCard.js
  src/index.js
  src/pages/Averages.js
  src/redux/actions/actionTypes.js
  src/redux/actions/averageActions.js
  src/redux/reducers/averageValuesReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
Labels: frontend

#33 Frontend/25 Day-5 #25
  .env
  package-lock.json
  package.json
  src/api/config/client.js
  src/api/config/config.js
  src/api/config/headers.js
  src/api/config/methods.js
  src/api/config/request.js
  src/api/config/statusCodes.js
  src/api/measurements.js
  src/assets/styles/components/Header.scss
  src/assets/styles/components/MeasurementCard.scss
  src/assets/styles/pages/Averages.scss
  src/common/utils.js
  src/components/Header.js
  src/components/MeasurementCard.js
  src/index.js
  src/pages/Averages.js
  src/redux/actions/actionTypes.js
  src/redux/actions/averageActions.js
  src/redux/configureStore.js
  src/redux/reducers/averageValuesReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
Labels: epic, frontend

#38 Create All data page #36
  package-lock.json
  src/App.scss
  src/Routes.js
  src/assets/styles/components/AllDataCard.scss
  src/assets/styles/components/MeasurementCard.scss
  src/assets/styles/pages/AllData.scss
  src/assets/styles/variables.scss
  src/components/AllDataCard.js
  src/components/AllDataCardRow.js
  src/components/AverageCard.js
  src/components/Header.js
  src/components/index.js
  src/hooks/useDates.js
  src/hooks/useWindowDimensions.js
  src/pages/AllData.js
  src/pages/Averages.js
  src/pages/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/averageActions.js
  src/redux/actions/measurementsActions.js
  src/redux/reducers/averageValuesReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/measurementsReducer.js
Labels: enhancement

#39 frontend/34 Day-6 #34
  package-lock.json
  src/App.scss
  src/Routes.js
  src/assets/styles/components/AllDataCard.scss
  src/assets/styles/components/MeasurementCard.scss
  src/assets/styles/pages/AllData.scss
  src/assets/styles/variables.scss
  src/components/AllDataCard.js
  src/components/AllDataCardRow.js
  src/components/AverageCard.js
  src/components/Header.js
  src/components/index.js
  src/hooks/useDates.js
  src/hooks/useWindowDimensions.js
  src/pages/AllData.js
  src/pages/Averages.js
  src/pages/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/averageActions.js
  src/redux/actions/measurementsActions.js
  src/redux/reducers/averageValuesReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/measurementsReducer.js
Labels: epic, frontend

#41 frontend/37 Implement filters functionality
  package-lock.json
  package.json
  src/App.scss
  src/Routes.js
  src/assets/icons/ConfirmFilter.js
  src/assets/icons/HumidityOff.js
  src/assets/icons/HumidityOn.js
  src/assets/icons/OpenFilter.js
  src/assets/icons/PollutionOff.js
  src/assets/icons/PollutionOn.js
  src/assets/icons/TemperatureIcon.js
  src/assets/icons/TemperatureOff.js
  src/assets/icons/TemperatureOn.js
  src/assets/icons/index.js
  src/assets/styles/components/Filters.scss
  src/assets/styles/components/Header.scss
  src/assets/styles/variables.scss
  src/components/AllDataCard.js
  src/components/AllDataCardRow.js
  src/components/AverageCard.js
  src/components/Filters.js
  src/components/Header.js
  src/components/index.js
  src/pages/Averages.js
  src/redux/actions/actionTypes.js
  src/redux/actions/averageActions.js
  src/redux/actions/measurementsActions.js
  src/redux/actions/selectedTypesActions.js
  src/redux/reducers/averageValuesReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/selectedTypesReducer.js
Labels: frontend

#43 frontend/42 Adjust style for Filter component #42
  src/assets/styles/components/Filters.scss
  src/components/Filters.js
Labels: frontend

#46 frontend/45 Change initial state for measurements reducer #45
  src/redux/reducers/initialState.js
Labels: frontend

#47 frontend/44 The Average page is displaying data from previous state #44
  src/pages/Averages.js
  src/redux/actions/actionTypes.js
  src/redux/actions/averageActions.js
  src/redux/reducers/averageValuesReducer.js
Labels: frontend

#48 frontend/35 Day-7 #35
  package-lock.json
  package.json
  src/assets/icons/ConfirmFilter.js
  src/assets/icons/HumidityOff.js
  src/assets/icons/HumidityOn.js
  src/assets/icons/OpenFilter.js
  src/assets/icons/PollutionOff.js
  src/assets/icons/PollutionOn.js
  src/assets/icons/TemperatureIcon.js
  src/assets/icons/TemperatureOff.js
  src/assets/icons/TemperatureOn.js
  src/assets/icons/index.js
  src/assets/styles/components/Filters.scss
  src/assets/styles/components/Header.scss
  src/assets/styles/variables.scss
  src/components/AverageCard.js
  src/components/Filters.js
  src/components/Header.js
  src/components/index.js
  src/pages/Averages.js
  src/redux/actions/actionTypes.js
  src/redux/actions/averageActions.js
  src/redux/actions/measurementsActions.js
  src/redux/actions/selectedTypesActions.js
  src/redux/reducers/averageValuesReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/initialState.js
  src/redux/reducers/selectedTypesReducer.js
Labels: epic, frontend
